service: my-local-service
provider:
  name: aws
  runtime: python3.8
  stage: v1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello   # La ruta debe coincidir con lo que estás accediendo
          method: post   # O el método HTTP que estás utilizando


plugins:
  - serverless-offline